### ISSUE TITLE
Does not work with new Newspapers.com layout

### ISSUE THREAD

**Issue by reader5567** [jp-x-g/PressPass#2]
It seems like Newspapers.com has updated their page layout (see this screenshot: https://imgur.com/a/NiOEZQj) and it's broken the citation on clipping pages. I cannot find the citation text to copy-and-paste. Everything else seems to be working, but I don't use any other features so I might be missing something.

**Comment by FormalDude** [comment]
Same problem. See screenshot below of [newspapers.com/article/the-akron-beacon-journal-barney-gets-his/129461267](https://www.newspapers.com/article/the-akron-beacon-journal-barney-gets-his/129461267/).
![Screenshot 2023-08-04 at 22-17-54 Barney Gets His - Newspapers com](https://github.com/jp-x-g/PressPass/assets/133025275/e1cc955d-b14f-496b-9f57-98ac49fc9232)

**Comment by jp-x-g** [comment]
This should be fixed in the new release, 2.1: it's been revised for image page and article pages (the new "/clip"). Documentation updated for the new layout as well. Let me know if there is anything messed up about it now.
